# -*- coding: utf-8 -*-
"""감정호응도_구현 (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wEmYAPzEAPoD5dzetdXrqXinIK9scnS5

## 기본 감정분류 모델 구축
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/Colab Notebooks/Emotion/

!pip install mxnet
!pip install gluonnlp pandas tqdm
!pip install sentencepiece
!pip install transformers==3
!pip install torch==1.12.1

!pip install git+https://git@github.com/SKTBrain/KoBERT.git@master

import torch
from torch import nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import gluonnlp as nlp
import numpy as np
from tqdm import tqdm, tqdm_notebook

from kobert.utils import get_tokenizer
from kobert.pytorch_kobert import get_pytorch_kobert_model

from transformers import AdamW
from transformers.optimization import get_cosine_schedule_with_warmup
import warnings
warnings.filterwarnings(action='ignore')

device = torch.device("cuda:0")

bertmodel, vocab = get_pytorch_kobert_model()

import pandas as pd
df = pd.read_csv('감정 분류 데이터셋.csv',encoding='cp949')
df = df.iloc[:, [1, 2]]
df2 = pd.read_excel('speech.xlsx')

df3 = df2.iloc[1:2000,[1,2]]
df3.columns=['대화', '감정']

df.loc[(df['1번 감정'] == "angry"), '1번 감정'] = 0
df.loc[(df['1번 감정'] == "anger"), '1번 감정'] = 0
df.loc[(df['1번 감정'] == "disgust"), '1번 감정'] = 0
df.loc[(df['1번 감정'] == "fear"), '1번 감정'] = 0
df.loc[(df['1번 감정'] == "sadness"), '1번 감정'] = 0
df.loc[(df['1번 감정'] == "sad"), '1번 감정'] = 0
df.loc[(df['1번 감정'] == "neutral"), '1번 감정'] = 1
df.loc[(df['1번 감정'] == "surprise"), '1번 감정'] = 1
df.loc[(df['1번 감정'] == "happiness"), '1번 감정'] = 2
df.columns=['대화', '감정']

df3.loc[(df3['감정'] == "슬픔"), '감정'] = 0
df3.loc[(df3['감정'] == "공포"), '감정'] = 0
df3.loc[(df3['감정'] == "혐오"), '감정'] = 0
df3.loc[(df3['감정'] == "분노"), '감정'] = 0
df3.loc[(df3['감정'] == "부정"), '감정'] = 0
df3.loc[(df3['감정'] == "중립"), '감정'] = 1
df3.loc[(df3['감정'] == "놀람"), '감정'] = 1
df3.loc[(df3['감정'] == "행복"), '감정'] = 2
df3.loc[(df3['감정'] == "긍정"), '감정'] = 2

df_test = pd.read_csv('emotion_labeling.csv', encoding='cp949')
df_test.loc[(df_test['감정'] == '공포'), '감정'] = 0
df_test.loc[(df_test['감정'] == '분노'), '감정'] = 0
df_test.loc[(df_test['감정'] == '슬픔'), '감정'] = 0
df_test.loc[(df_test['감정'] == '혐오'), '감정'] = 0
df_test.loc[(df_test['감정'] == '부정'), '감정'] = 0
df_test.loc[(df_test['감정'] == '놀람'), '감정'] = 1
df_test.loc[(df_test['감정'] == '중립'), '감정'] = 1
df_test.loc[(df_test['감정'] == '긍정'), '감정'] = 2

print(np.unique(df['감정']))
print(np.unique(df_test.감정))

train_df = pd.concat([df, df3])
test_df = df_test

train = []
for q, label in zip(train_df['대화'], train_df['감정'])  :
    data = []
    data.append(q)
    data.append(str(label))

    train.append(data)

test = []
for q, label in zip(test_df['대화'], test_df['감정'])  :
    data = []
    data.append(q)
    data.append(str(label))

    test.append(data)

class BERTDataset(Dataset):
    def __init__(self, dataset, sent_idx, label_idx, bert_tokenizer, max_len, pad, pair):
        transform = nlp.data.BERTSentenceTransform(bert_tokenizer, max_seq_length=max_len, pad=pad, pair=pair)
        self.sentences = [transform([i[sent_idx]]) for i in dataset]
        self.labels = [np.int32(i[label_idx]) for i in dataset]

    def __getitem__(self, i):
        return (self.sentences[i] + (self.labels[i], ))

    def __len__(self):
        return (len(self.labels))

# Setting parameters
max_len = 64
batch_size = 64
warmup_ratio = 0.1
num_epochs = 5
max_grad_norm = 1
log_interval = 200
learning_rate = 5e-5

#토큰화
tokenizer = get_tokenizer()
tok = nlp.data.BERTSPTokenizer(tokenizer, vocab, lower=False)

data_train = BERTDataset(train, 0, 1, tok, max_len, True, False)
data_test = BERTDataset(test, 0, 1, tok, max_len, True, False)

train_dataloader = torch.utils.data.DataLoader(data_train, batch_size=batch_size, num_workers=5)
test_dataloader = torch.utils.data.DataLoader(data_test, batch_size=batch_size, num_workers=5)

class BERTClassifier(nn.Module):
    def __init__(self,
                 bert,
                 hidden_size = 768,
                 num_classes = 3, # softmax 사용 <- binary일 경우는 2
                 dr_rate=None,
                 params=None):
        super(BERTClassifier, self).__init__()
        self.bert = bert
        self.dr_rate = dr_rate

        self.classifier = nn.Linear(hidden_size , num_classes)
        if dr_rate:
            self.dropout = nn.Dropout(p=dr_rate)

    def gen_attention_mask(self, token_ids, valid_length):
        attention_mask = torch.zeros_like(token_ids)
        for i, v in enumerate(valid_length):
            attention_mask[i][:v] = 1
        return attention_mask.float()

    def forward(self, token_ids, valid_length, segment_ids):
        attention_mask = self.gen_attention_mask(token_ids, valid_length)

        _, pooler = self.bert(input_ids = token_ids, token_type_ids = segment_ids.long(), attention_mask = attention_mask.float().to(token_ids.device))
        if self.dr_rate:
            out = self.dropout(pooler)
        return self.classifier(out)

model = BERTClassifier(bertmodel, dr_rate=0.5).to(device)

no_decay = ['bias', 'LayerNorm.weight']
optimizer_grouped_parameters = [
    {'params': [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)], 'weight_decay': 0.01},
    {'params': [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)], 'weight_decay': 0.0}
]

# 옵티마이저 선언
optimizer = AdamW(optimizer_grouped_parameters, lr=learning_rate)
loss_fn = nn.CrossEntropyLoss() # softmax용 Loss Function 정하기 <- binary classification도 해당 loss function 사용 가능

t_total = len(train_dataloader) * num_epochs
warmup_step = int(t_total * warmup_ratio)

scheduler = get_cosine_schedule_with_warmup(optimizer, num_warmup_steps=warmup_step, num_training_steps=t_total)

def calc_accuracy(X,Y):
    max_vals, max_indices = torch.max(X, 1)
    train_acc = (max_indices == Y).sum().data.cpu().numpy()/max_indices.size()[0]
    return train_acc

import torch, gc
gc.collect()
torch.cuda.empty_cache()

for e in range(num_epochs):
    train_acc = 0.0
    test_acc = 0.0

    model.train()
    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm_notebook(train_dataloader)):
        optimizer.zero_grad()
        token_ids = token_ids.long().to(device)
        segment_ids = segment_ids.long().to(device)
        valid_length= valid_length
        label = label.long().to(device)
        out = model(token_ids, valid_length, segment_ids)
        loss = loss_fn(out, label)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm) # gradient clipping
        optimizer.step()
        scheduler.step()  # Update learning rate schedule
        train_acc += calc_accuracy(out, label)
        if batch_id % log_interval == 0:
            print("epoch {} batch id {} loss {} train acc {}".format(e+1, batch_id+1, loss.data.cpu().numpy(), train_acc / (batch_id+1)))
    print("epoch {} train acc {}".format(e+1, train_acc / (batch_id+1)))

    model.eval() # 평가 모드로 변경

    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm_notebook(test_dataloader)):
        token_ids = token_ids.long().to(device)
        segment_ids = segment_ids.long().to(device)
        valid_length= valid_length
        label = label.long().to(device)
        out = model(token_ids, valid_length, segment_ids)
        test_acc += calc_accuracy(out, label)
    print("epoch {} test acc {}".format(e+1, test_acc / (batch_id+1)))

def classify_emotion(sentences):    # 감정 분류 함수

  unseen_values = pd.DataFrame([[sentences, 0]], columns = [['대화 내용', '감정']]).values
  test_set = BERTDataset(unseen_values, 0, 1, tok, max_len, True, False)
  test_input = torch.utils.data.DataLoader(test_set, batch_size=1, num_workers=5)

  for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(test_input):
    token_ids = token_ids.long().to(device)
    segment_ids = segment_ids.long().to(device)
    valid_length= valid_length
    out = model(token_ids, valid_length, segment_ids)
    max_vals, max_indices = torch.max(out, 1)

    temp = max_indices.data.cpu().numpy()
    if temp == [0]:
      final_value = -1
    elif temp == [1]:
      final_value = 0
    else:
      final_value = 1

  return final_value

# 예시문장
classify_emotion('생크림은 질색이야')

"""## 예시 문장"""

import time

def score_1(sentences_list): # 점수 측정 함수
    start = time.time()
    X = []
    for i in range(len(sentences_list)):

      x_1 = classify_emotion(sentences_list[i])

      if i == 0:
        x_2 = (classify_emotion(sentences_list[i]) + classify_emotion(sentences_list[i+1]))/2
      elif i == (len(sentences_list)-1):
        x_2 = (classify_emotion(sentences_list[i]) + classify_emotion(sentences_list[i-1]))/2
      else:
        x_2 = (classify_emotion(sentences_list[i]) + classify_emotion(sentences_list[i-1]) + classify_emotion(sentences_list[i+1]) )/3

      X_3 = 0
      for i in range(len(sentences_list)):
        temp = classify_emotion(sentences_list[i])
        X_3 = X_3 + temp

      x_3 = X_3 / len(sentences_list)

      x = x_1*0.4 + x_2*0.3 + x_3*0.3
      X.append(x)
      end = time.time() - start
    return(X, end)

def score_2(sentences_list): # 점수 측정 함수
    start = time.time()
    X = list(0 for i in range(len(sentences_list)))
    X_1 = list(0 for i in range(len(sentences_list)))
    X_2 = list(0 for i in range(len(sentences_list)))
    X_3 = 0

    for i in range(len(sentences_list)):
      X_1[i]= classify_emotion(sentences_list[i])
    X_3 = np.mean(X_1)
    for i in range(len(sentences_list)):
      if i == 0:
        x_2 = (X_1[i] +X_1[i+1])/2
      elif i == (len(sentences_list)-1):
        x_2 = (X_1[i] + X_1[i-1])/2
      else:
        x_2 = (X_1[i] + X_1[i-1] + X_1[i+1])/3
      X_2[i] = x_2

      X[i]= X_1[i]*0.4 + X_2[i]*0.3 + X_3*0.3
      end = time.time()
    return(X, end-start)

sent_1 = ['끝나고 디저트 카페 어때요?',
        '그럼요~ 여기 쇼트케이크 진짜 맛있어요!',
        ' 아뇨,, 뭐 그냥 크게 걱정 안해요. ㅋㅋ 먹고 싶은 거 먹는 거죠 뭐',
        ' 그래요? 싫어하는 사람도 있구나, 그럼 초콜릿은요? 초콜릿 진짜 맛있어요!']

sent_2 = ['아.. 디저트요? 좀 곤란한데요.. 좋아하시나요?',
          '하아.. 저는 디저트로 뚱뚱해지는게 싫어요.. 그런 걱정 안하시나봐요..',
          '대단하시네요. 전 생크림은 질색이에요.',
          '초콜릿도 잘 안 먹어요..ㅠㅠ']

score_1 = score_1(sent_1)
score_1

score_1 = score_2(sent_1)
score_1

score_2 = score(sent_2)
score_2

import matplotlib.pyplot as plt
plt.plot(score_1, label='Person 1')
plt.plot(score_2, color='red', label='Person 2')
plt.ylim(-1, 1)
plt.legend()
plt.show()

sent_3 = ['오늘 저녁 뭐 드셨어요?',
      '와~ 맛있으셨나요?',
      '저는 로제 떡볶이 먹어본 적 없어요.. 어떤 맛인가요?',
      '네 궁금하네요 ㅋㅋㅋ 한번 먹어봐야겠어요!',
      '전 김치찌개 먹었어요! 저는 저희 집 김치찌개가 젤 맛있는 것 같아요 ㅋㅋ',
      '저는 참치 넣는 것 좋아해요',
      '엄마표가 최고에요 진짜 ㅋㅋ']

sent_4 = ['오늘은 떡군이네 떡볶이라는 곳에서 로제 떡볶이 시켜 먹었어요.',
          '네 맛있더라고요. 한창 유행일 때는 잘 안 먹엇는데, 뒤늦게 자주 먹고 있어요.',
          '약간 떡 같은데 좀 더 쫄깃한 맛이에요. 나중에 한번 드셔보세요.',
          '꼭 배민에서 시켜 드세요. 거기꺼가 맛있어요. ㅋㅋ 혹시 저녁 뭐 드셨나요?',
          '역시 김치찌개 맛있죠! 뭐 넣어 드시는 거 좋아하세요?',
          '저희 엄마도 참치 좋아하셔서 언제나 참치 김치찌개에요.',
          '그렇죠 ㅋㅋ']

score_3 = score(sent_3)
score_3

score_4 = score(sent_4)
score_4

import matplotlib.pyplot as plt
plt.plot(score_3, label='Person 1')
plt.plot(score_4, color='red', label='Person 2')
plt.ylim(-1, 1)
plt.legend()
plt.show()

"""## 최종 도출"""

import pandas as pd
df4 = pd.read_csv('df4.csv')
df4 = df4.iloc[6000:8000, 3:27]

person_1 = []
person_2 = []
for i in range(len(df4)):
  sent_person_1 = []
  sent_person_2 = []
  for i2 in range(24):
    if (i2 %2 == 0) & (str(df4.iloc[i, i2]) != 'nan'):
      sent_person_1.append(df4.iloc[i,i2])
    elif (i2 %2 ==1) & (str(df4.iloc[i, i2]) != 'nan'):
      sent_person_2.append(df4.iloc[i,i2])

  person_1.append(sent_person_1)
  person_2.append(sent_person_2)

def score_final(sentences_list): # 점수 측정 함수
    X = list(0 for i in range(len(sentences_list)))
    X_1 = list(0 for i in range(len(sentences_list)))
    X_2 = list(0 for i in range(len(sentences_list)))
    X_3 = 0

    for i in range(len(sentences_list)):
      X_1[i]= classify_emotion(sentences_list[i])
    X_3 = np.mean(X_1)
    for i in range(len(sentences_list)):
      if i == 0:
        x_2 = (X_1[i] +X_1[i+1])/2
      elif i == (len(sentences_list)-1):
        x_2 = (X_1[i] + X_1[i-1])/2
      else:
        x_2 = (X_1[i] + X_1[i-1] + X_1[i+1])/3
      X_2[i] = x_2

      X[i]= X_1[i]*0.6 + X_2[i]*0.3 + X_3*0.1

    return(X)

scores_1 = []
scores_2 = []
for i in range(len(df4)):
  scores_1.append(score_final(person_1[i]))
  scores_2.append(score_final(person_2[i]))

pip install dtaidistance

from dtaidistance import dtw

distance = []
for i in range(len(scores_1)):
  distance.append(dtw.distance(scores_1[i], scores_2[i]))

len(distance)

df = pd.DataFrame(distance)
df.columns = ['distance']

from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
scaler = MinMaxScaler()
df.distance = scaler.fit_transform(df.distance.values.reshape(-1, 1))
plt.hist(df.distance);

df['similarity'] = df['distance'].map(lambda x: 1-x)

df = df.drop(columns = 'distance')
df.describe()

df

plt.hist(df.similarity)

df.to_csv('final_scores.csv')